# Generated by Django 6.0.1 on 2026-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
